# Generated by Django 4.1 on 2023-11-06 17:00

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):
    dependencies = [
        ("hacks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hack",
            name="content",
            field=djrichtextfield.models.RichTextField(max_length=1000000),
        ),
    ]
